# **Handling Missing Values**

In [1]:
import pandas as pd
import numpy as np

In [44]:
# reading a data-set
data_frame=pd.read_csv(r'D:\Desktop\Data_Science\Pandas\Datasets\lesson_2\datasets-session-17\diabetes.csv')

In [45]:
df=data_frame.copy()

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
# Checking for Null values
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
df.loc[0:110, "Insulin"] = np.nan

In [9]:
df.isnull().sum()

Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                     111
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [10]:
df1=df.copy()

## **1. Dropping columns and rows having Missing Values**

In [ ]:
df.dropna(axis=1) #removes insulin column

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,33.6,0.627,50,1
1,1,85,66,29,26.6,0.351,31,0
2,8,183,64,0,23.3,0.672,32,1
3,1,89,66,23,28.1,0.167,21,0
4,0,137,40,35,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
763,10,101,76,48,32.9,0.171,63,0
764,2,122,70,27,36.8,0.340,27,0
765,5,121,72,23,26.2,0.245,30,0
766,1,126,60,0,30.1,0.349,47,1
767,1,93,70,31,30.4,0.315,23,0

In [16]:
df1.iloc[45:182]=np.nan

In [17]:
df1.isnull().sum()

Pregnancies                 137
Glucose                     137
BloodPressure               137
SkinThickness               137
Insulin                     182
BMI                         137
DiabetesPedigreeFunction    137
Age                         137
Outcome                     137
dtype: int64

In [18]:
df1.isnull().sum().sum()

np.int64(1278)

In [20]:
df1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,NaN,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,NaN,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,NaN,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0.0

In [21]:
df1.dropna(axis=0)# removing rows having null values

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
182,1.0,0.0,74.0,20.0,23.0,27.7,0.299,21.0,0.0
183,5.0,73.0,60.0,0.0,0.0,26.8,0.268,27.0,0.0
184,4.0,141.0,74.0,0.0,0.0,27.6,0.244,40.0,0.0
185,7.0,194.0,68.0,28.0,0.0,35.9,0.745,41.0,1.0
186,8.0,181.0,68.0,36.0,495.0,30.1,0.615,60.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0.0

## **2. Filling Rows or Columns having Missing values**

In [22]:
df2=df.copy()

In [27]:
# filling using mean of remaining values
df2["Insulin"].isnull().sum()

np.int64(111)

In [26]:
df2['Insulin'].mean()

np.float64(81.17199391171994)

In [30]:
df2=df2['Insulin'].fillna(df2['Insulin'].mean())

In [32]:
df2

0       81.171994
1       81.171994
2       81.171994
3       81.171994
4       81.171994
          ...
763    180.000000
764      0.000000
765    112.000000
766      0.000000
767      0.000000
Name: Insulin, Length: 768, dtype: float64

In [33]:
df2.isnull().sum()

np.int64(0)

In [34]:
df.iloc[42:93]=np.nan

In [35]:
df.isnull().sum()

Pregnancies                  51
Glucose                      51
BloodPressure                51
SkinThickness                51
Insulin                     111
BMI                          51
DiabetesPedigreeFunction     51
Age                          51
Outcome                      51
dtype: int64

In [41]:
df.iloc[42:93]=df.iloc[42:93].fillna('Missing')

C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')
C:\Users\ASK\AppData\Local\Temp\ipykernel_31528\3206910401.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing' 'Missing'
 'Missing' 'Missing']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[42:93]=df.iloc[42:93].fillna('Missing')

In [43]:
df.iloc[42:93]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
42,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
43,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
44,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
45,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
46,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
47,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
48,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
49,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
50,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
51,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
52,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
53,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
54,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
55,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
56,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
57,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
58,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
59,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
60,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
61,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
62,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
63,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
64,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
65,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
66,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
67,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
68,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
69,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
70,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
71,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
72,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
73,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
74,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
75,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
76,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
77,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
78,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
79,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
80,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
81,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
82,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
83,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
84,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
85,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
86,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
87,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
88,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
89,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
90,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
91,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing
92,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing

In [46]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [47]:
# Creating Missing Values
df.loc[45:92,'Age']=np.nan

In [48]:
df.isnull().sum()

Pregnancies                  0
Glucose                      0
BloodPressure                0
SkinThickness                0
Insulin                      0
BMI                          0
DiabetesPedigreeFunction     0
Age                         48
Outcome                      0
dtype: int64

In [50]:
df.loc[45:92,'Age']=df.loc[45:92,'Age'].fillna(df['Age'].mode()[0])

In [51]:
df.loc[45:92,'Age']

45    22.0
46    22.0
47    22.0
48    22.0
49    22.0
50    22.0
51    22.0
52    22.0
53    22.0
54    22.0
55    22.0
56    22.0
57    22.0
58    22.0
59    22.0
60    22.0
61    22.0
62    22.0
63    22.0
64    22.0
65    22.0
66    22.0
67    22.0
68    22.0
69    22.0
70    22.0
71    22.0
72    22.0
73    22.0
74    22.0
75    22.0
76    22.0
77    22.0
78    22.0
79    22.0
80    22.0
81    22.0
82    22.0
83    22.0
84    22.0
85    22.0
86    22.0
87    22.0
88    22.0
89    22.0
90    22.0
91    22.0
92    22.0
Name: Age, dtype: float64

In [52]:
data_frame.isnull().mean().sort_values(ascending=False)

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
Outcome                     0.0
dtype: float64

In [53]:
df3=pd.read_csv(r"D:\Desktop\Data_Science\Pandas\Datasets\lesson_2\datasets-session-17\ipl-matches.csv")

In [55]:
df3.isnull().sum().sort_values(ascending=False)

method             931
City                51
Margin              18
SuperOver            4
Player_of_Match      4
WinningTeam          4
ID                   0
Date                 0
Season               0
Venue                0
MatchNumber          0
Team1                0
TossWinner           0
TossDecision         0
Team2                0
WonBy                0
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [56]:
df3['method']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
945    NaN
946    NaN
947    NaN
948    NaN
949    NaN
Name: method, Length: 950, dtype: object

In [59]:
df3['method']=df3['method'].bfill()

In [60]:
df3.isnull().sum()

ID                  0
City               51
Date                0
Season              0
MatchNumber         0
Team1               0
Team2               0
Venue               0
TossWinner          0
TossDecision        0
SuperOver           4
WinningTeam         4
WonBy               0
Margin             18
method             39
Player_of_Match     4
Team1Players        0
Team2Players        0
Umpire1             0
Umpire2             0
dtype: int64